### ISSUE TITLE
OntoPro does not include the type "^^date" in the query results

### ISSUE THREAD

**Issue by fanavarro** [ontop/ontop#179]
### Description
I'm using OntoPro to perform queries. Normally the result includes the datatype, for example 3^^int or "example"^^string. However, when the result type is a date, it does not appear. Because of this, when I perform a materialization of triples, the dates do not have a specified type, which is causing inconsistencies when I use other reasoners on the ontology.
### Steps to Reproduce

1. Create a test database. For example, a database with a unique table called PERSON with the following colums:
    ID (NUMBER)
    NAME (VARCHAR)
    SURNAME (VARCHAR)
    BIRTH (DATE)
2. Add a person to the table ;-):
![imagen](https://cloud.githubusercontent.com/assets/11376639/23512126/d7609540-ff5f-11e6-8e81-df969297498f.png)

3. Create the ontology with a Person class and hasBirth, hasId, hasName and hasSurname data properties:
![imagen](https://cloud.githubusercontent.com/assets/11376639/23512211/2b99fca0-ff60-11e6-8631-5663d2f72e0c.png)
All the properties have Person as domain. The properties hasName and hasSurname have xsd:string as range. The property hasId has xsd:int as range. The property hasBirth has xsd:date as range.

4. Create the mapping as follows:
![imagen](https://cloud.githubusercontent.com/assets/11376639/23512329/88611e78-ff60-11e6-86e5-783d7087e098.png)

5. Start ontop reasoner and perform the following query:
select * where {
	?person a :Person ;
		:hasId ?id ;
		:hasName ?name ;
		:hasSurname ?surname ;
		:hasBirth ?birth .
}
**Expected behavior:** 
Each result must be paired with their type:
"1"^^xsd:int	"skomlaebri"^^xsd:string	"theBest"^^xsd:string	"1989-03-18"^^date
**Actual behavior:** 
The date appears without the type:
![imagen](https://cloud.githubusercontent.com/assets/11376639/23522679/2cfd904c-ff84-11e6-865a-58efc1c58611.png)

### Versions
Ontop OBDA Protege Plugin 1.18.0
Protege 5.0.0

**Comment by ghxiao** [comment]
Could you try to put the type in the mapping: {BIRTH}^^xsd:date ?

**Comment by fanavarro** [comment]
Hi @ghxiao , thanks for your answer.
The query fails when I put the type in the mapping:
![imagen](https://cloud.githubusercontent.com/assets/11376639/23542569/5169140a-ffee-11e6-9556-57896e7a6e15.png)

![imagen](https://cloud.githubusercontent.com/assets/11376639/23542599/6d5986fe-ffee-11e6-8430-502c15a00101.png)

I think the format of the date is correct according to the [xml schema](https://www.w3schools.com/xml/schema_dtypes_date.asp).

**Comment by ghxiao** [comment]
Strange. Could you copy/paste the log?

**Comment by fanavarro** [comment]
Hi again @ghxiao . I think this error is not being registered in the log. The log is empty when I open it after the error:
![imagen](https://cloud.githubusercontent.com/assets/11376639/23601388/806ad89c-024b-11e7-8f1e-81d049a34eb2.png)

![imagen](https://cloud.githubusercontent.com/assets/11376639/23601425/aa8bf822-024b-11e7-98a8-a65310d72c1f.png)

However, when I start Protege from the terminal, this message appears several times when I start the reasoner:
![imagen](https://cloud.githubusercontent.com/assets/11376639/23601665/ed7560dc-024c-11e7-83ef-498a7ea0af33.png)
I think this is happening due to the date format in the query.
Then, when I perform the query, the following exception appears in the terminal:
![imagen](https://cloud.githubusercontent.com/assets/11376639/23601738/4193b164-024d-11e7-9b16-2eb32772a231.png)

Is it possible that there is a conflict with my locale? I'm from Spain so the dates normally are dd-mm-yyyy. Maybe this causes the exception.

**Comment by fanavarro** [comment]
Hi, I've been debugging a little and I think I've figured out what is happening.
The application executes the following code from the method getConstant of QuestTupleResultSet:
```
case DATE:
	if (!isOracle) {
		Date dvalue = rs.getDate(column);
		result = fac.getConstantLiteral(dvalue.toString(), COL_TYPE.DATE);
	} 
	else {
		try {
			DateFormat df = new SimpleDateFormat("dd-MMM-yy" ,  Locale.ENGLISH);
			java.util.Date date = df.parse(value);
		} 
		catch (ParseException e) {
			throw new RuntimeException(e);
		}
		result = fac.getConstantLiteral(value.toString(), COL_TYPE.DATE);
	}
break;
```
It try to create a Date object from the string "1989-03-18" but it is expecting "1989-mar-18", which causes the crash. My database is oracle. Maybe this code was designed to manage the raw output from the database whose locale is supposed to be English. Due to the xsd:date format is yyyy-mm-dd, I force it in the mapping directly by the using of TO_CHAR. However, if I remove TO_CHAR function, the database returns 1989-03-18 12:38:36.0 and it fails again at query time:
![imagen](https://cloud.githubusercontent.com/assets/11376639/23604942/0c9873a6-025b-11e7-93ce-f64b4afd6ee1.png)
What is the best way to deal with this?

**Comment by ghxiao** [comment]
@fanavarro We are working on a hot fix now.

**Comment by ghxiao** [comment]
@fanavarro Could you check the latest ontop v3-beta-1?

**Comment by fanavarro** [comment]
Hi @ghxiao, thanks for your answer.
I've tried the new beta version with the same example described in this issue and it is throwing the following error on the reasoner startup:

![imagen](https://user-images.githubusercontent.com/11376639/29960898-c62a3186-8efd-11e7-8e20-14d835251e8b.png)

The reasoner can start if I change the range of hasId property to xsd:string, but this error is strange because in the database the id column contains a NUMBER(38,0) datatype (oracle database).

In this point, if I leave the mapping without datatype specified, the type of the date appears as xsd:string instead of xsd:date (should it be string or date?):

![imagen](https://user-images.githubusercontent.com/11376639/29961179-057a3baa-8eff-11e7-9783-dd451f775bf5.png)

![imagen](https://user-images.githubusercontent.com/11376639/29961203-16cf49cc-8eff-11e7-90ab-4e856487f3f9.png)

However, if I put the ^^xsd:date on the mapping, the query finishes in error:

![imagen](https://user-images.githubusercontent.com/11376639/29961240-3bb6c5da-8eff-11e7-89ba-89d9fc6fa406.png)

![imagen](https://user-images.githubusercontent.com/11376639/29961291-6714b0d4-8eff-11e7-8342-4736eb98a36b.png)

The terminal is showing the following trace:
```
it.unibz.inf.ontop.owlapi.exception.OntopOWLException: it.unibz.inf.ontop.exception.OntopResultConversionException: it.unibz.inf.ontop.exception.OntopResultConversionException: java.text.ParseException: Unparseable date: "1989-03-18" Column: 5
	at it.unibz.inf.ontop.owlapi.resultset.impl.OntopOWLBindingSet.getOWLPropertyAssertionObject(OntopOWLBindingSet.java:59)
	at it.unibz.inf.ontop.protege.gui.OWLResultSetTableModel.fetchRows(OWLResultSetTableModel.java:168)
	at it.unibz.inf.ontop.protege.gui.OWLResultSetTableModel.access$200(OWLResultSetTableModel.java:37)
	at it.unibz.inf.ontop.protege.gui.OWLResultSetTableModel$1.run(OWLResultSetTableModel.java:115)
```
Thanks again.

**Comment by skomlaebri** [comment]
Hi, 
I confirm the presence of two different issues:
1- Unrecognized datatype of the database column  (string is the default value returned)
The problem can be avoided inserting the datatype information inside the target (ex.  :hasId {ID}^^xsd:date) or simplifying the SQL query avoiding the use of functions that we currently do not support (ex. removing to_char function SELECT ID, NAME, SURNAME, BIRTH FROM PERSON)
The problem infact appears only with select query that we are not able to parse ( in this case due to the presence of the to_char function).
2-the to_char function should not be needed to get the correct  xsd:date result. We are working to fix xsd:date output format so that it will respect the standard yyyy-mm-dd

**Comment by skomlaebri** [comment]
Fixed in 2e2dff39e94a146adc79d058473528f27f30da51

**Comment by ispbox** [comment]
I've tested new fix (ontop beta 2), but it looks like it still doesn't work with dates under the following conditions:
- Oracle
- Windows
- Not English locale
Under these conditions when I try to select columns that contain date in mapping window, I get correct values like 2018-03-29. But when I execute SPARQL query that uses this mapping, the resulting message from ontop is the following:
Error when fetching results. Aborting. ..... OntopResultConversionException: unparseable datetime: 29.03.2018 Column 3.
I guess the problem is with locale.
Using of to_char function helps, but that breaks optimization of SQL statements, and they execute longer than desired.

**Comment by gqjiang** [comment]
Use ontop-cli 3.0 and sounds like that it can not handle the date format "2160-3-7". any suggestion on this? thanks,

java.lang.RuntimeException: it.unibz.inf.ontop.exception.OntopResultConversionException: it.unibz.inf.ontop.exception.OntopResultConversionException: unparseable datetime: 2160-3-7
	at it.unibz.inf.ontop.rdf4j.query.impl.OntopRDF4JBindingSet.convertBinding(OntopRDF4JBindingSet.java:98)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at org.eclipse.rdf4j.query.resultio.sparqljson.AbstractSPARQLJSONWriter.handleSolution(AbstractSPARQLJSONWriter.java:170)
	at org.eclipse.rdf4j.query.resultio.sparqljson.SPARQLResultsJSONWriter.handleSolution(SPARQLResultsJSONWriter.java:19)
	at it.unibz.inf.ontop.rdf4j.query.impl.OntopTupleQuery.evaluate(OntopTupleQuery.java:87)
	at it.unibz.inf.ontop.endpoint.SparqlQueryController.execQuery(SparqlQueryController.java:145)
	at it.unibz.inf.ontop.endpoint.SparqlQueryController.query_post_URL_encoded(SparqlQueryController.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: it.unibz.inf.ontop.exception.OntopResultConversionException: it.unibz.inf.ontop.exception.OntopResultConversionException: unparseable datetime: 2160-3-7
	at it.unibz.inf.ontop.answering.resultset.impl.JDBC2ConstantConverter.getConstantFromJDBC(JDBC2ConstantConverter.java:246)
	at it.unibz.inf.ontop.answering.resultset.impl.SQLOntopBinding.getValue(SQLOntopBinding.java:26)
	at it.unibz.inf.ontop.rdf4j.query.impl.OntopRDF4JBindingSet.convertBinding(OntopRDF4JBindingSet.java:95)
	... 75 more
Caused by: it.unibz.inf.ontop.exception.OntopResultConversionException: unparseable datetime: 2160-3-7
	at it.unibz.inf.ontop.answering.resultset.impl.JDBC2ConstantConverter.convertToJavaDate(JDBC2ConstantConverter.java:302)
	at it.unibz.inf.ontop.answering.resultset.impl.JDBC2ConstantConverter.getConstantFromJDBC(JDBC2ConstantConverter.java:212)
	... 77 more

**Comment by gqjiang** [comment]
It turns out that the date format has to be in "2160-03-07"^^xsd:date, instead of in "2160-3-7"^^xsd:date. but the challenge is that we assembled the date from year, month and day like 

mappingId	Person-birthDate2
target		:birthDate :value "{year_of_birth}-{month_of_birth}-{day_of_birth}"^^xsd:date . 
source		select * from "person"

It is not easy to generate correct format from obda mapping. It will be very helpful if the ontop API can handle this. thanks,

**Comment by gqjiang** [comment]
Resolved.
mappingId	Person-birthDate3
target		:birthData :value "{year_of_birth}-0{month_of_birth}-0{day_of_birth}"^^xsd:date . 
source		select * from person" where "month_of_birth"<10 and "day_of_birth"<10
